variables:
  secchi: ["Depth, Secchi disk depth", "Depth, Secchi disk depth (choice list)", "Secchi Reading Condition (choice list)", "Secchi depth", "Water transparency, Secchi disc"]
  temperature: ["Temperature, sample", "Temperature, water","Temperature"]

sb_ids:
  secchi: "??"
  temperature: "56eaefdae4b0f59b85d919dd"

columnsToKeep: ["ActivityStartDate","ActivityStartTime.Time","ActivityStartTime.TimeZoneCode","ActivityBottomDepthHeightMeasure.MeasureValue","ActivityBottomDepthHeightMeasure.MeasureUnitCode","MonitoringLocationIdentifier","ResultMeasureValue","ResultMeasure.MeasureUnitCode"]      

# WQP startDateLo and startDateHi    
startDate: "1979-01-01"
endDate: "2015-12-31"


siteType: "Lake, Reservoir, Impoundment"

yearSplit: 2
